// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id PROJECT_REF > src/lib/database.types.ts

// Type for JSON/JSONB fields in Supabase
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder Database type - will be replaced with auto-generated types
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          username: string | null
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          username?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          username?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      songs: {
        Row: {
          id: string
          title: string
          artist: string | null
          slug: string
          composition_year: number | null
          ccli: string | null
          themes: string[]
          source: string | null
          notes: string | null
          default_arrangement_id: string | null
          // Multilingual lyrics support
          lyrics: Json | null           // JSONB in database: {"en": "...", "ja": "...", "ja-romaji": "...", "ko": "...", "ko-romaji": "..."}
          original_language: string | null  // Native script only: 'en', 'ja', 'ko'
          lyrics_verified: boolean
          lyrics_source: string | null
          auto_conversion_enabled: boolean // For future Romaji auto-conversion
          created_by: string | null
          is_public: boolean
          rating_average: number
          rating_count: number
          views: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          artist?: string | null
          slug: string
          composition_year?: number | null
          ccli?: string | null
          themes?: string[]
          source?: string | null
          notes?: string | null
          default_arrangement_id?: string | null
          // Multilingual lyrics support
          lyrics?: Json | null
          original_language?: string | null
          lyrics_verified?: boolean
          lyrics_source?: string | null
          auto_conversion_enabled?: boolean
          created_by?: string | null
          is_public?: boolean
          rating_average?: number
          rating_count?: number
          views?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          artist?: string | null
          slug?: string
          composition_year?: number | null
          ccli?: string | null
          themes?: string[]
          source?: string | null
          notes?: string | null
          default_arrangement_id?: string | null
          // Multilingual lyrics support
          lyrics?: Json | null
          original_language?: string | null
          lyrics_verified?: boolean
          lyrics_source?: string | null
          auto_conversion_enabled?: boolean
          created_by?: string | null
          is_public?: boolean
          rating_average?: number
          rating_count?: number
          views?: number
          created_at?: string
          updated_at?: string
        }
      }
      arrangements: {
        Row: {
          id: string
          name: string
          song_id: string
          slug: string
          chord_data: string
          key: string | null
          tempo: number | null
          time_signature: string
          difficulty: string | null
          description: string | null
          tags: string[]
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          song_id: string
          slug: string
          chord_data: string
          key?: string | null
          tempo?: number | null
          time_signature?: string
          difficulty?: string | null
          description?: string | null
          tags?: string[]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          song_id?: string
          slug?: string
          chord_data?: string
          key?: string | null
          tempo?: number | null
          time_signature?: string
          difficulty?: string | null
          description?: string | null
          tags?: string[]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      setlists: {
        Row: {
          id: string
          name: string
          description: string | null
          created_by: string | null
          is_public: boolean
          share_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          created_by?: string | null
          is_public?: boolean
          share_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          created_by?: string | null
          is_public?: boolean
          share_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      setlist_items: {
        Row: {
          id: string
          setlist_id: string
          arrangement_id: string | null
          position: number
          notes: string | null
        }
        Insert: {
          id?: string
          setlist_id: string
          arrangement_id?: string | null
          position: number
          notes?: string | null
        }
        Update: {
          id?: string
          setlist_id?: string
          arrangement_id?: string | null
          position?: number
          notes?: string | null
        }
      }
      reviews: {
        Row: {
          id: string
          song_id: string
          user_id: string
          rating: number
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          song_id: string
          user_id: string
          rating: number
          comment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          song_id?: string
          user_id?: string
          rating?: number
          comment?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}